=== E3SM-Project/giac/iac/gcam/cvs/objects/model_data/schemas/configuration.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Josh Lurz (PNNL) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Configuration">
		<xs:annotation>
			<xs:documentation>Contains configuration values for CIAM</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Files" type="strType" />
				<xs:element name="Strings" type="strType" />
				<xs:element name="Bools">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Value" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:int">
											<xs:attribute name="name" type="xs:string" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Ints">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Value" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:int">
											<xs:attribute name="name" type="xs:string" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Doubles">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Value" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:double">
											<xs:attribute name="name" type="xs:string" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="strType">
		<xs:sequence>
			<xs:element name="Value" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name" type="xs:string" use="required" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== E3SM-Project/giac/iac/gcam/exe/configuration_exp1_clmcarbon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Josh Lurz (PNNL) -->
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:/cvs/Code/Ciam/Configuration.xsd">
	<Files>
		<Value name="erbInputFileName">./erbinput2.csv</Value>
		<Value name="outFileName">outFile.csv</Value>
		<Value name="bugOutFileName">bugoutfile.csv</Value>
		<Value name="logOutFileName">logfile.csv</Value>
		<Value name="climatFileName">gas.emk</Value>
		<Value name="xmlInputFileName">./core_model_input.xml</Value>
		<Value name="xmlOutputFileName">./output.xml</Value>
		<Value name="xmlDebugFileName">debug.xml</Value>
		<Value name="sdCurveFileName">sdcurve.csv</Value>
		<Value name="sdFileName">sdall.csv</Value>
		<Value name="dbOutFileName">dbout.csv</Value>
		<Value name="dbFileName">./output.mdb</Value>
		<Value name="supplyDemandOutputFileName">SDCurves.csv</Value>
		<Value name="xmldb-location">./database.dbxml</Value>
		<Value name="GHGInputFileName">./input_gases.emk</Value>
		<Value name="dependencyGraphName">DependencyGraph</Value>
		<Value name="policy-target-file">./policy_target.xml</Value>
		<Value name="BatchFileName">batch_emf.xml</Value>
	</Files>
	<ScenarioComponents>
		<Value name="solver_config">./solver_config.xml</Value>
		<Value name="tax">./carbon_tax_4p5.xml</Value>
	</ScenarioComponents>
	<Strings>
		<Value name="scenarioName">RCP4p5_exp1_2035</Value>
	</Strings>
	<Bools>
		<Value name="debugChecking">0</Value>
		<Value name="write-access-db">0</Value>
		<Value name="write-xml-db">1</Value>
		<Value name="BatchMode">0</Value>
		<Value name="timestamp">0</Value>
		<Value name="agSectorActive">0</Value>
		<Value name="agSubsidy">1</Value>
		<Value name="agBioMarketSet">0</Value>
		<Value name="simulActive">1</Value>
		<Value name="CalibrationActive">0</Value>
		<Value name="trackMaxED">0</Value>
		<Value name="PrintDependencyGraphs">0</Value>
		<Value name="PrintValuesOnGraphs">1</Value>
		<Value name="debugFindSD">0</Value>
		<Value name="PrintSectorDependencies">0</Value>
		<Value name="ShowNullPaths">0</Value>
		<Value name="PrintPrices">1</Value>
		<Value name="createCostCurve">0</Value>
		<Value name="estimateCosts">0</Value>
		<Value name="find-path">0</Value>
		<Value name="addLUCtoMarket">1</Value>
	</Bools>
	<Ints>
		<Value name="numMarketsToFindSD">10</Value>
		<Value name="numPointsForSD">21</Value>
		<Value name="numPointsForCO2CostCurve">5</Value>
		<Value name="carbon-output-start-year">1705</Value>
		<Value name="climateOutputInterval">5</Value>
	</Ints>
	<Doubles>
	</Doubles>
</Configuration>

=== E3SM-Project/giac/iac/gcam/cvs/objects/configuration_files/templates/configuration_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Josh Lurz (PNNL) -->
<Configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:/cvs/Code/Ciam/Configuration.xsd">
	<Files>
		<!--START User Modifiable Variables-->
		<Value name="xmlInputFileName">../cvs/objects/model_data/base/base_input.xml</Value>
		<Value name="xmlOutputFileName">../output/output.xml</Value>
		<Value name="BatchFileName">BatchFile.xml</Value>
		<Value name="sPolicyInputFileName">sPolInput.xml</Value>
		<!--END User Modifiable variables-->
		<!--START Developer Only Modifiable Variables-->
		<Value name="outFileName">../output/outFile.csv</Value>
		<Value name="climatFileName">gas.emk</Value>
		<Value name="xmlDebugFileName">../output/debug.xml</Value>
		<Value name="ObjectSGMFileName">../output/ObjectSGMout.csv</Value>
		<Value name="ObjectSGMGenFileName">../output/ObjectSGMGen.csv</Value>
		<Value name="xmldb-location">../output/database.dbxml</Value>
		<Value name="dbFileName">../output/output.mdb</Value>
		<Value name="supplyDemandOutputFileName">../output/SDCurves.csv</Value>
		<Value name="GHGInputFileName">../cvs/objects/magicc/inputs/input_gases.emk</Value>
		<Value name="dependencyGraphName">../output/DependencyGraph</Value>
		<Value name="landAllocatorGraphName">../output/LandAllocatorGraph</Value>
		<Value name="costCurvesOutputFileName">../output/cost_curves.xml</Value>
		<!--END Developer Only Modifiable Variables-->
	</Files>
	<ScenarioComponents>
		<!--START User Modifiable Variables-->
		<Value name="B2Calibration">../cvs/objects/model_data/scenario_components/sres_scenarios/b2_calibration.xml</Value>
		<!--END User Modifiable variables-->
	</ScenarioComponents>
	<Strings>
		<!--START User Modifiable Variables-->
		<Value name="scenarioName"></Value>
		<Value name="region-to-graph">USA</Value>
		<!--END User Modifiable variables-->
		<!--START Developer Only Modifiable Variables-->
		<Value name="debug-region">USA</Value>
		<Value name="AbatedGasForCostCurves">CO2</Value>
		<Value name="monitorMktName">China</Value>
		<Value name="monitorMktGood"></Value>
		<Value name="SolverName">BisectionNRSolver</Value>
		<!--END Developer Only Modifiable Variables-->
	</Strings>
	<Bools>
		<!--START User Modifiable Variables-->
		<Value name="CalibrationActive">1</Value>
		<Value name="createCostCurve">0</Value>
		<Value name="BatchMode">0</Value>
		<Value name="find-path">0</Value>
		<Value name="simple-find-path">0</Value>
		<Value name="PrintDependencyGraphs">0</Value>
		<Value name="PrintValuesOnGraphs">0</Value>
		<Value name="PrintPrices">1</Value>
		<Value name="write-access-db">1</Value>
		<Value name="write-xml-db">1</Value>
		<Value name="agSubsidy">0</Value>
		<!--END User Modifiable variables-->
		<!--START Developer Only Modifiable Variables-->
		<Value name="debugChecking">0</Value>
		<Value name="agSectorActive">1</Value>
		<Value name="agBioMarketSet">0</Value>
		<Value name="simulActive">1</Value>
		<Value name="debugFindSD">0</Value>
		<Value name="PrintSectorDependencies">0</Value>
		<Value name="ShowNullPaths">0</Value>
		<Value name="mergeFilesOnly">0</Value>
		<!--END Developer Only Modifiable Variables-->
	</Bools>
	<Ints>
		<Value name="discount-start-year">2005</Value>
		<Value name="land-use-history-interval">5</Value>
		<Value name="carbon-stock-output-interval">5</Value>
		<Value name="carbon-output-start-year">1900</Value>
		<Value name="climateOutputInterval">15</Value>
		<!--START Developer Only Modifiable Variables-->
		<Value name="numMarketsToFindSD">10</Value>
		<Value name="numPointsForSD">21</Value>
		<Value name="numPointsForCO2CostCurve">5</Value>
		<!--END Developer Only Modifiable Variables-->
	</Ints>
	<Doubles>
		<!--START User Modifiable Variables-->
		<Value name="discountRate">0.05</Value>
		<Value name="SolutionTolerance">0.001</Value>
		<Value name="SolutionFloor">0.01</Value>
		<!--END User Modifiable variables-->
		<Value name="bracket-interval">0.5</Value>
		<Value name="DeltaPrice">0.00001</Value>
	</Doubles>
</Configuration>
